words = [
    "acc",
    "aoe",
    "appshell",
    "arktype",
    "backlink",
    "bloodthirst",
    "breakpoint",
    "brewmaster",
    "caeser",
    "crit",
    "homebrew",
    "linkgroup",
    "mantine",
    "miw",
    "omni",
    "oxlint",
    "reviver",
    "rotz",
    "scaler",
    "shapeshift",
    "splitter",
    "ssr",
    "stddev",
    "subarchetype",
    "subarchetypes",
    "supabase",
    "tanky",
    "targetted",
    "targetting",
    "userbutton",
    "zombeast",
    "zombrero",
    "zustand",
]
